export const CATS_LOADING = 'CATS_LOADING';
export const ADD_CATS = 'ADD_CATS';
export const CATS_FAILED = 'CATS_FAILED';

export const ADD_FAVORITECAT = 'ADD_FAVORITECAT';
export const DELETE_FAVORITECAT = 'DELETE_FAVORITECAT'; 